basePath: /api
definitions:
  auth.LoginUserDto:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterUserDto:
    properties:
      email:
        type: string
      name:
        minLength: 3
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  workspace.CreateWorkspaceDto:
    properties:
      name:
        maxLength: 195
        minLength: 3
        type: string
      slug:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
  description: This is a jira clone api docs.
  title: jira clone api
  version: "1.0"
paths:
  /v1/auth/info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - '[Auth] {v1}'
  /v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginUserDto'
      produces:
      - application/json
      responses: {}
      tags:
      - '[Auth] {v1}'
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - '[Auth] {v1}'
  /v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterUserDto'
      produces:
      - application/json
      responses: {}
      tags:
      - '[Auth] {v1}'
  /v1/workspace:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - '[Workspace] {v1}'
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/workspace.CreateWorkspaceDto'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - '[Workspace] {v1}'
  /v1/workspace/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: workspace id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - '[Workspace] {v1}'
swagger: "2.0"
