basePath: /api
info:
  contact: {}
  description: This is a jira clone api docs.
  title: jira clone api
  version: "1.0"
paths:
  /v1/auth:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - users
swagger: "2.0"
